plugins { id 'com.android.application' }
android {
    namespace 'com.cardio.lab'
    compileSdk 36
    defaultConfig {
        applicationId 'com.cardio.lab'
        minSdk 26
        targetSdk 34
        versionCode 26
        versionName '0.26-km'
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_1_8; targetCompatibility JavaVersion.VERSION_1_8 }
}
