plugins { id 'com.android.application' }

android {
    namespace 'com.cardio.diagnostic'
    compileSdk 36
    defaultConfig {
        applicationId 'com.cardio.diagnostic'
        minSdk 31
        targetSdk 34
        versionCode 1
        versionName '0.1'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
